version: "3.8"

services:
  node:
    build:
      context: ./node
    command:
      - "-datadir=/data"
    volumes:
      - "bitcoin_data:/data"

volumes:
  bitcoin_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${PWD}/data'